exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: flake8
      args: ['--ignore=E203, E266, E501, W503, F403, F401']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.650
    hooks:
    -   id: mypy